--- #YAML:1.0
name:               Mplayer-NowPlaying
version:            0.030
abstract:           Query a running Mplayer process for metadata
author:
    - Magnus Woldrich <trapd00r@trapd00r.se>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:  {}
requires:
    Test::More:  0
resources:
    bugtracker:  https://github.com/trapd00r/Mplayer-NowPlaying/issues
    repository:  https://github.com/trapd00r/Mplayer-NowPlaying
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
